# Generated by Django 2.0 on 2021-09-14 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailvarifyrecord',
            name='code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='验证码'),
        ),
        migrations.AlterField(
            model_name='emailvarifyrecord',
            name='send_time',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='发送时间'),
        ),
        migrations.AlterField(
            model_name='emailvarifyrecord',
            name='send_type',
            field=models.CharField(choices=[('register', '注册'), ('forget', '忘记密码')], max_length=50, verbose_name='验证码类型'),
        ),
    ]
