# Generated by Django 2.0 on 2021-09-13 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_auto_20210913_0731'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='img',
            field=models.ImageField(default='', upload_to='courses/%Y/%m', verbose_name='头像'),
        ),
    ]
