# Generated by Django 2.0 on 2021-10-22 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0011_auto_20210922_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='degree',
            field=models.CharField(choices=[('cj', 'primary'), ('zj', 'intermediate'), ('gj', 'senior')], max_length=2, verbose_name='difficult'),
        ),
    ]
